# Generated by Django 2.2.6 on 2019-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
