# Generated by Django 2.2.6 on 2019-11-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20191121_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='mobile',
        ),
    ]
